# Generated by Django 4.2.27 on 2026-01-24 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de identificación debe tener entre 8 y 20 dígitos', regex='^\\d{8,20}$')]),
        ),
    ]
