# Generated by Django 4.2.27 on 2026-01-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_categoria_options_alter_categoria_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0005_historialdecompras_alter_pedidos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('En Proceso', 'En Proceso'), ('Entregado', 'Entregado'), ('En Devolución', 'En Devolución'), ('Devuelto', 'Devuelto')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('Solicitada', 'Solicitada'), ('En Proceso', 'En Proceso'), ('Devuelta', 'Devuelta'), ('Rechazada', 'Rechazada')], default='Solicitada', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='compras.pedidos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.devolucion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'unique_together': {('devolucion', 'libro')},
            },
        ),
    ]
